apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: con-hello
  namespace: hello
spec:
  ports:
    - name: "30003"
      port: 30003
      targetPort: 5000
  selector:
    app: hello
