apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: u34-fun-facts-ingress
  namespace: u34-fun-facts
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: u34-fun-facts-web
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: con-web
            port:
              number: 8888
