- name: HW Ansible Build, Push, and Run Docker Image
  hosts: localhost
  gather_facts: false

  vars_files:
    - dockerhub_pass.yml

  vars:
    app_folder: "/home/meto/work/Upskill_34_DevOps/tests/ansible-docker/application"
    git_repo: "Metodil/devops-programme"
    image_name: "my-hello-world"
    image_tag: "v0."
    container_name: "my-hello-world-hw"
    listen_port:
      - "5000:3000"

  tasks:
    - name: Get version number
      local_action: shell file=$((`cat ver_num` + 1)); echo $file | tee ver_num
      register: ver_num

    - name: Print Version number
      debug:
        var: "{{ image_tag }}{{ ver_num.stdout }}"

    - name: Create application directory
      file:
        path: "{{ app_folder }}"
        state: directory
        mode: 0777

    - name: Get latest git version
      git:
        repo: git@github.com:{{ git_repo }}
        dest: "{{ app_folder }}"
        version: main
        force: true

    - name: Build Docker image
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}"
        source: build
        build:
          path: "{{ app_folder }}"
          args:
            log_volume: /var/log/{{ image_name }}
        tag: "{{ image_tag }}{{ ver_num.stdout }}-vault"
        state: present

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Push Docker image to registry
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}"
        tag: "{{ image_tag }}{{ ver_num.stdout }}-vault"
        push: true
        source: local

    - name: Stop container
      docker_container:
        state: absent
        name: "{{ container_name }}"

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ dockerhub_username }}/{{ image_name }}:{{ image_tag }}{{ ver_num.stdout }}-vault"
        state: started
        ports: "{{ listen_port }}"
